### ISSUE TITLE
[Comp-Req]: Skeleton Loader

### ISSUE THREAD

**Issue by warflash** [fantasyflip/nuxtwind#54]
**Component Name**
NXW-Skeleton

**Use-case**
Make loading state more user friendly by showing a temporary placeholder skeleton

**Example**
https://vuetifyjs.com/en/components/skeleton-loaders/#usage

**Comment by fantasyflip** [comment]
added in version [0.7.0](https://github.com/fantasyflip/nuxtwind/releases/tag/v0.7.0)
